services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - ./volumes/static:/opt/static
      - ./volumes/media:/opt/media
      - ./volumes/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
  postgres:
    image: postgres:14.17
    environment:
      POSTGRES_PASSWORD: 'ralph_ng'
      POSTGRES_USER: 'ralph_ng'
      POSTGRES_DB: 'ralph_ng'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./volumes/psql:/var/lib/postgresql/data/pgdata
    command: "postgres -c log_statement='all'"
    ports:
      - "54320:5432"
  redis:
    platform: linux/amd64
    image: redis:4.0
    ports:
      - "6379:6379"
  inkpy:
    build:
      context: ../
      dockerfile: docker/Dockerfile-inkpy
    image: allegro/inkpy:20250414.1
    depends_on:
     - redis
    platform: linux/amd64
    restart: always
    environment:
        REDIS_HOST: redis
        REDIS_PASSWORD: ""
        REDIS_PORT: 6379
        REDIS_DB: 0

